### ISSUE TITLE
Pop!_OS 21.04: installation guide with btrfs 

### ISSUE THREAD

**Issue by Tealk** [wmutschl/mutschler.eu#21]
Hello,

I have a question about the "systemd bootloader and kernelstub" part. Do you have to repeat it after updating e.g. release 21.10  or kernel update?

**Comment by wmutschl** [comment]
Not for kernel updates. I am not sure about release upgrades. I remember upgrading 20.04 directly to 20.10, which worked flawlessly. So I would think that this change will typically stick. Of course, if not, then you simply chroot into your system from the recovery system or a live system, redo that change, update the initramfs and you are good to go.

**Comment by Tealk** [comment]
Super thanks for due explanations.
I've been looking into different distros (because I'm not sure what I want to use yet) and many just make one big btrfs partition without subvolumes. Are you creating the subvolumes because of the fragmentation problem (if there still is one with btrfs) or because of the timeshift backup?

**Comment by 8W3oybHJdYzBex** [comment]
> Super thanks for the explanations. I've been looking into different distros (because I'm not sure what I want to use yet) and many just make one big btrfs partition without subvolumes. Are you creating the subvolumes because of the fragmentation problem (if there still is one with btrfs) or because of the timeshift backup?

Timeshift, in btrfs mode, looks for subvolumes `@` and `@home`. That is a [hardcoded requirement](https://github.com/teejee2008/timeshift/issues/370) at this time, though it [seems likely to change](https://github.com/archlinux/archinstall/issues/781). This doesn't matter if using Timeshift in rsync mode, but that also defeats the point of using btrfs instead of ext4.

Timeshift aside, there is still a valid reason to use subvolumes: [for the same reasons as having separate home and root partitions on the same drive](https://www.reddit.com/r/archlinux/comments/5b6gb8/btrfs_partitions_or_subvolumes/). In this context, subvolumes are (more or less) functionally identical to partitions, except without fixed sizes. Separating home and root allows you to reinstall Pop!_OS or even install multiple distros simultaneously without messing with your home folder.

As far as I know, there aren't really any downsides to using subvolumes in this manner, so you should use them if setting up a system with btrfs. It's understandable if you want to use subvolume names/layouts different from the Ubuntu/Timeshift defaults, but I wouldn't recommend foregoing subvolumes entirely.
