### ISSUE TITLE
Full disk and BTRBK steps to delete sub volume

### ISSUE THREAD

**Issue by msmafra** [wmutschl/mutschler.eu#33]
Hello there!

Your guide was very helpful since I'm also not able to use Timeshift since Fedora 34 (nor even with fresh installation for testing).
It was amazing being able to upgrade to Fedora 36 beta and get back to Fedora 35 after some very, very strange behaviours with a beta system that I was already testing on my external SSD.

So, I used the default Fedora sub volumes and your configuration for BTRBK. It didn't take much time, my system started behaving strangely, after a half hour, some checks on DNF history, Flatpak and Brave browser, out of nowhere (and finally) my Gnome decided to warn me that I was getting out of free space (less than 500MB). I about 100GB free before upgrading to F36.

When I tested TimeShift, I had the same problem, but a bit more because with TimeShift it caused the BTRFS partition to get completely full. As I was just testing, I did a fresh install and restore my backups via Restic.
I setted it on my main drive, 500GB and also to send it to my external USB 1TB drive.
Not sure if there is a way with BTRBK to set and minimum of free space to be alerted, or if I will have to create a script to keep checking it and alert me.

When restoring, I went to the BTRBK git page to follow the instructions. Restoring was really fast and easy, I even double-checked (it's been a while since I used _btrfs send_ and _btrfs receive_ and other commands) if I did things right. Rebooted and everything was there. BUT probably a BTRFS thing, I couldn't delete the Broken sub volume. Kept saying that wasn't empty, even trying with _rm_ and _rmdir_ from another system, and I was just able to do it by removing each folder corresponding to previous snapshots.

All this just to say that is not yet a set-and-forget solution, but not needing to rename sub volumes is already a very super advantage.

**Comment by wmutschl** [comment]
Thanks for your experience. Your problem was probably due to the use of rm and rmdir, because you need to delete subvolumes using `sudo btrfs subvolume delete NAMEOFBROKENSUBVOL`. You can specify retention policies both with BTRBK and Timeshift, but remember btrfs is copy-on-write. So if you have a fedora 35 system and you make a snapshot of this and then update to fedora 36 many many files will change and you basically need to have space for two systems at the same time. So manually removing very old snapshots is a good idea (honestly, I never needed to restore something from / from last year or last month, but mostly from an hour ago or from yesterday). `btrfs-du` is a nice project to show how much space your snapshots take on your disk.
