### ISSUE TITLE
Question: upgrade from Pop OS 20.04 to 22.04

### ISSUE THREAD

**Issue by OxygenLiu** [wmutschl/mutschler.eu#34]
I have a setup of 20.04 according to instructions at https://mutschler.eu/linux/install-guides/pop-os-btrfs-raid1-20-04/ . What is the best practice on upgrading to 22.04? 

+ Backup all data on separate drive, fresh install of 22.04, and restore the data? 
+ Live update on top of existing system?  Any precautions?

**Comment by wmutschl** [comment]
Usually, you can just do a live update.
Step 1: MAKE A BTRFS SNAPSHOT!
Step 2: MAKE AN ADDITIONAL OFFSIDE BACKUP!
Step 3: Follow the steps outlined [here](https://support.system76.com/articles/upgrade-pop/).

I will do it now on my server and report back :-)

**Comment by wmutschl** [comment]
Okay, it hangs at reboot while doing
```
/scripts/init-bottom
/scripts/local-bottom
```
I need to investigate this further.

**Comment by wmutschl** [comment]
Okay, the issue was that my system drive had no space left. So I booted into recovery, mounted the system drive and deleted a huge folder to have a couple of gigs available again. Restart and boom I am running Pop!_OS 22.04.
So before running the upgrade, make sure you have enough free space available, e.g. looking at
```
sudo btrfs fi usage /
```
Long story short: Live update works!
